### ISSUE TITLE
Warnings when compiling

### ISSUE THREAD

**Issue by stevehunt100** [ladyada/Adafruit_CharacterOLED#11]
Just using the provided example sketch HelloOLEDWorld gives:

F:\Documents\Arduino\libraries\Adafruit_CharacterO LED-master\Adafruit_CharacterOLED.cpp:66:101: warning: default argument given for parameter 3 of 'void Adafruit_CharacterOLED::begin(uint8_t, uint8_t, uint8_t)' [-fpermissive]
void Adafruit_CharacterOLED::begin(uint8_t cols, uint8_t lines, uint8_t character_set = LCD_JAPANESE)
^
In file included from F:\Documents\Arduino\libraries\Adafruit_CharacterO LED-master\Adafruit_CharacterOLED.cpp:7:0:
F:\Documents\Arduino\libraries\Adafruit_CharacterO LED-master\Adafruit_CharacterOLED.h:58:8: note: previous specification in 'void Adafruit_CharacterOLED::begin(uint8_t, uint8_t, uint8_t)' here
void begin(uint8_t cols, uint8_t rows, uint8_t character_set = LCD_JAPANESE);
^
F:\Documents\Arduino\libraries\Adafruit_CharacterO LED-master\Adafruit_CharacterOLED.cpp: In member function 'virtual size_t Adafruit_CharacterOLED::write(uint8_t)':
F:\Documents\Arduino\libraries\Adafruit_CharacterO LED-master\Adafruit_CharacterOLED.cpp:244:1: warning: no return statement in function returning non-void [-Wreturn-type]
}
^

in the cpp file, changing void Adafruit_CharacterOLED::begin(uint8_t cols, uint8_t lines, uint8_t character_set = LCD_JAPANESE)
to
void Adafruit_CharacterOLED::begin(uint8_t cols, uint8_t lines, uint8_t character_set)
fixes the first warning (should I have to do this???) but the warning still remails:

F:\Documents\Arduino\libraries\Adafruit_CharacterOLED-master\Adafruit_CharacterOLED.cpp: In member function 'virtual size_t Adafruit_CharacterOLED::write(uint8_t)':
F:\Documents\Arduino\libraries\Adafruit_CharacterOLED-master\Adafruit_CharacterOLED.cpp:244:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^

Is this a bug or what should I do?  Thanks

**Comment by ladyada** [comment]
you can ignore them or submit a PR to update the library if you like

**Comment by stevehunt100** [comment]
You want me to fix this for you?  No.  I'm reporting a bug.  Please fix your software!
